### ISSUE TITLE
Complete lumber harvesting mechanics

### ISSUE THREAD

**Issue by cowsforyou** [cowsforyou/barracks_master_2#46]
- [x] Create workers for Xoya - cows
- [x] Create workers for Ling - cows 
- [x] Create manual spawn code - noya
- [x] Create harvesting ability/system - noya
- [x] Create indicator for remaining lumber amount on Giant Tree - noya

**Comment by cowsforyou** [comment]
Gonna assign the manual spawn code to you instead @MNoya because I think it arches on something bigger which is creating a table to track the player networth: https://github.com/cowsforyou/barracks_master_2/issues/24. And that involves a whole lot of stuff.

**Comment by cowsforyou** [comment]
Basically the manual spawn code should allow the player to spawn workers that appear next to the lumber building. It should check for a max_count kv that would be housed in the spawner ability kv file.

Each faction will have different workers. This is the [Xoya](https://github.com/cowsforyou/barracks_master_2/blob/master/game/dota_addons/barracks_master_2/scripts/npc/units/xoya/xoya_worker_dendro.txt) one and this is the [Ling ](https://github.com/cowsforyou/barracks_master_2/blob/master/game/dota_addons/barracks_master_2/scripts/npc/units/ling/ling_worker_nelum.txt)one.

**Comment by MNoya** [comment]
Made great progress with tree gathering, its almost done, just have some doubts:

1. I made the gather ability on the workers no-target, it will search the closest tree and gather from it. For specific-tree targeting, right-clicking the tree will send the worker to gather on that tree. Is that allright?
2. The closest-tree search will accept trees that the player hasn't discoverd/has no vision of. Should that be prevented?
3. I added a behaviour for the lumber depot building, when clicking on a giant tree, it will create particle so that all workers will go to gather from that tree instead of their current one (and also be sent directly there on spawn). I haven't implemented the last part yet, only the particle, does it sound desirable?
4. Current lumber per second gatherer is 1 and max is 10, I just put those numbers inside the functions to test the scripts, do we need them to be dynamic (i.e. can values change during the game, maybe via upgrades?)
5. Should the ancient be a valid lumber deposit? If it's not, keep in mind the workers might not have a valid lumber depot after it is destroyed. 
6. In addition, I think the ancient should be the one to build these workers, instead of them spawning from the lumber depot, this secondary building would just be used for tech/faster travel time.
7. I made the workers spawn automatically without a channel time for faster testing, let me know how it should be.

**Comment by cowsforyou** [comment]
1) That's fine!
2) That's fine too. However, not all trees can be accessed normally as I've blocked them off using trees. So the player has to manually chop the regular trees to get to it. We'll need to make the AI know to only gather from trees that have a valid path.
3) Interesting ability. If you've already done it, then that's fantastic. But if not, then it's only a nice to have at this point.
4) We don't need dynamic numbers so the 1-10 max is a good placeholder for now. I will probably tweak it later to have it at a fixed no. eg 5 per second. The lumber/gold modifiers will only be done upon deposit, eg a 1.5x multiplier when you drop off the lumber. These abilities will be on the Purifier.
5) The only valid lumber deposit would be the Lumber Depot. The player will have to rebuild it if he wants to continue collecting lumber. We currently have it setup to allow a max building count of 3 anyway so they will likely have multiple!
6) I generally don't want to touch the ancient/towers for any player related things since we have more than 1 player per team (up to 4). So spawning it from the Lumber Depot would make it more straightforward.
7) The spawn should be manual with a cooldown. I'm trying to make the multitasking element a big part of the game. If you want faster testing we can have the cooldown set to 1 second in the meantime :)

**Comment by cowsforyou** [comment]
Almost done with this issue! Just need to add the remaining lumber on tree. @MNoya

**Comment by MNoya** [comment]
Isn't that just the HP remaining on the tree? I thought that was already in

**Comment by cowsforyou** [comment]
Eh really? I thought the tree was invulerable. Haha. Ill go double check.
But that works too then! :)

**Comment by cowsforyou** [comment]
Ok just checked it out. Looks perfect! My apologies I didn't notice it before. Closing issue.
